services:
  postgres:
    image: postgres:15
    container_name: serp-postgres
    environment:
      POSTGRES_DB: serp
      POSTGRES_USER: serp
      POSTGRES_PASSWORD: serp_pw
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
